#!/bin/bash -ex

main() {  
  docker compose exec secrets-provider /bin/sh -c "
      echo 'Listing Annotations on disk...'
      cat /conjur/podinfo/annotations

      echo 'Listing API Key on disk...'
      cat /var/run/conjur/api-key

      echo 'Listing Secrets on disk...'
      echo
      cat /conjur/secrets/*
  "
}

main
