#!/bin/bash -ex

main() {  
  CONJUR_ACCOUNT=cucumber
  RESOURCE_KIND=user
  ROLE_ID=admin

  API_KEY=$(
    docker compose exec -T conjur \
      conjurctl role retrieve-key $CONJUR_ACCOUNT:$RESOURCE_KIND:$ROLE_ID | tr -d '\r'
  )

  TOKEN=$(docker compose exec conjur curl \
        --silent \
        --insecure \
        --request POST \
        --data $API_KEY \
        "https://proxy/authn/$CONJUR_ACCOUNT/$ROLE_ID/authenticate" | base64 -w0)


  IDENTIFIER="example/alpha"
  VALUE="$(openssl rand -hex 32)"

  echo "Updating $IDENTIFIER to: $VALUE"
  docker compose exec conjur curl \
        --silent \
        --insecure \
        --request POST \
        --header "Authorization: Token token=\"$TOKEN\"" \
        --data "$VALUE" \
        https://proxy/secrets/$CONJUR_ACCOUNT/variable/$IDENTIFIER

  IDENTIFIER="example/beta"
  VALUE="$(openssl rand -hex 32)"

  echo "Updating $IDENTIFIER to: $VALUE"
  docker compose exec conjur curl \
        --silent \
        --insecure \
        --request POST \
        --header "Authorization: Token token=\"$TOKEN\"" \
        --data "$VALUE" \
        https://proxy/secrets/$CONJUR_ACCOUNT/variable/$IDENTIFIER
}

main
